# generated by datamodel-codegen:
#   filename:  task_schema.json
#   timestamp: 2025-12-29T13:06:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Extra


class OrchestratorTaskRequest(BaseModel):
    class Config:
        extra = Extra.forbid

    agent_name: str
    arguments: Any


class TaskStatus(Enum):
    pending = 'pending'
    running = 'running'
    completed = 'completed'
    failed = 'failed'


class TaskStatusResponse(BaseModel):
    class Config:
        extra = Extra.forbid

    task_id: str
    status: TaskStatus
    result: Any | None = None
    error: str | None = None


class TaskStartResponse(BaseModel):
    class Config:
        extra = Extra.forbid

    task_id: str
    status: TaskStatus


class Model(BaseModel):
    class Config:
        extra = Extra.forbid

    request: OrchestratorTaskRequest
    start_response: TaskStartResponse
    status_response: TaskStatusResponse
